services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npx prisma generate && npx prisma db push && npm run build && npm start"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_a
      POSTGRES_PASSWORD: user_a_password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: